-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 02-06-2022 a las 12:25:00
-- Versión del servidor: 8.0.29
-- Versión de PHP: 8.0.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `app_cursos`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `courses`
--

CREATE TABLE `courses` (
  `id` bigint UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `subtitle` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` enum('1','2','3') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '1',
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint UNSIGNED NOT NULL,
  `level_id` bigint UNSIGNED DEFAULT NULL,
  `category_id` bigint UNSIGNED DEFAULT NULL,
  `price_id` bigint UNSIGNED DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `ruta` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Volcado de datos para la tabla `courses`
--

INSERT INTO `courses` (`id`, `title`, `subtitle`, `description`, `status`, `slug`, `user_id`, `level_id`, `category_id`, `price_id`, `created_at`, `updated_at`, `ruta`) VALUES
(1, 'Veniam a ut enim quia.', 'Iusto voluptatem odit voluptas.', 'Ut quidem voluptas quasi est labore sed est natus. Et qui rerum nemo eaque impedit. Et sit id officiis molestias doloremque maxime.', '3', 'veniam-a-ut-enim-quia', 1, 1, 1, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(2, 'Accusantium non tempore qui vel ex in.', 'Laborum rerum minima officia eveniet.', 'Fugit non quas dolorem voluptate corrupti nemo. Dolorum recusandae laborum ipsum sit. Deserunt voluptas qui nulla aliquam nisi reprehenderit.', '3', 'accusantium-non-tempore-qui-vel-ex-in', 4, 3, 3, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(3, 'Et totam dolor dicta ipsam voluptates.', 'Non voluptatem accusamus velit nam.', 'Et quam blanditiis consequuntur labore exercitationem. Tempore ducimus iste aut voluptas. Accusantium rerum sed voluptas consequatur. Consequuntur facere ratione consequatur eos soluta.', '3', 'et-totam-dolor-dicta-ipsam-voluptates', 2, 2, 2, 4, '2022-05-18 14:58:29', '2022-05-19 12:01:58', NULL),
(4, 'Aut omnis quae voluptatem dolores totam rerum atque.', 'Animi qui perferendis labore autem et.', 'Et facere quod quo consequatur adipisci vitae corporis. Ipsa qui est molestias amet aut. Iste voluptatem dignissimos cumque et eos optio et quod.', '1', 'aut-omnis-quae-voluptatem-dolores-totam-rerum-atque', 2, 3, 3, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(5, 'Repellat et sed enim quod ex distinctio quis maxime.', 'Ad ut placeat fugit aut aut.', 'Possimus et dolore architecto. Aliquid fugiat excepturi totam est eius repellendus ad. Voluptatem quia autem quos. Quisquam rerum sit quo adipisci.', '1', 'repellat-et-sed-enim-quod-ex-distinctio-quis-maxime', 3, 2, 2, 2, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(6, 'Enim quasi nemo et sapiente quis voluptatem et.', 'Nam reprehenderit sapiente sed molestias.', 'Est nulla nihil voluptatem dolorum velit. Qui adipisci tempora perspiciatis molestiae. Maxime amet laborum aperiam vero quidem veniam.', '1', 'enim-quasi-nemo-et-sapiente-quis-voluptatem-et', 3, 1, 1, 4, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(7, 'Dolore fuga nihil doloribus non nam ut.', 'Sit hic commodi nihil ullam optio debitis.', 'Quis quaerat similique est dolorum. Nihil voluptatem doloremque id voluptas aut possimus est. Perspiciatis officiis amet temporibus repudiandae enim dolores ad. Quisquam provident et rerum suscipit voluptatem aut beatae.', '3', 'dolore-fuga-nihil-doloribus-non-nam-ut', 4, 3, 2, 3, '2022-05-18 14:58:29', '2022-05-19 13:18:51', NULL),
(8, 'Hic cupiditate excepturi nobis dolorem assumenda voluptas aut quia.', 'Laudantium sint quia consequuntur maxime asperiores exercitationem deleniti sunt.', 'Quo quas ipsa necessitatibus assumenda quas. Autem similique voluptatum eveniet in. Perspiciatis molestias sunt qui iste et dolorem necessitatibus. Aut error quia animi voluptatem.', '3', 'hic-cupiditate-excepturi-nobis-dolorem-assumenda-voluptas-aut-quia', 1, 3, 1, 2, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(9, 'Natus ullam dolorum totam velit.', 'Quia officiis est pariatur.', 'Quam nihil quibusdam dolores est. Architecto perspiciatis voluptas qui corrupti pariatur iusto pariatur quibusdam.', '3', 'natus-ullam-dolorum-totam-velit', 1, 1, 2, 4, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(10, 'Exercitationem ut omnis animi deserunt amet.', 'Quas omnis ut esse repellendus voluptas ex repellendus.', 'Inventore magni eius quidem qui laborum eveniet. Non eveniet saepe quia consequatur rem quaerat provident.', '1', 'exercitationem-ut-omnis-animi-deserunt-amet', 2, 2, 2, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(11, 'Veritatis deleniti ut et et odio labore.', 'Nesciunt suscipit iusto qui doloremque sunt.', 'Placeat doloremque explicabo dolorem non occaecati illum tempora. Necessitatibus delectus magni et sequi. Ipsum maxime ipsum commodi ut nisi. Ea maiores vel quidem voluptatem nisi.', '1', 'veritatis-deleniti-ut-et-et-odio-labore', 3, 1, 3, 4, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(12, 'Aspernatur fugit eaque sapiente ad.', 'Mollitia voluptas ut architecto qui nesciunt doloremque.', 'Consequatur architecto et quaerat et. Debitis perferendis at officiis error non. Expedita itaque est aperiam.', '3', 'aspernatur-fugit-eaque-sapiente-ad', 4, 2, 2, 2, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(13, 'Ut sed soluta sed qui voluptatum dolore et.', 'Aliquid repellat ut non laboriosam.', 'Officia tempore error optio error. Officia fugiat et repellat distinctio ipsam quo animi quia. Dolor modi consequatur commodi.', '1', 'ut-sed-soluta-sed-qui-voluptatum-dolore-et', 2, 2, 1, 1, '2022-05-18 14:58:29', '2022-05-27 14:12:54', NULL),
(14, 'Quae et earum ratione nesciunt.', 'Vero qui et aperiam praesentium nobis ut vel.', 'Fugit voluptate illo est qui ea ipsa non. Ut et magni et consequuntur. Qui neque excepturi aut in molestias.', '1', 'quae-et-earum-ratione-nesciunt', 2, 2, 1, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(15, 'Nam quasi exercitationem voluptates.', 'Suscipit ut et repudiandae aut aut molestiae nihil.', 'Dolorem quis eum accusantium accusamus placeat modi porro et. Et sit facilis et.', '3', 'nam-quasi-exercitationem-voluptates', 3, 3, 3, 3, '2022-05-18 14:58:29', '2022-05-19 13:19:00', NULL),
(16, 'Distinctio laudantium sunt deleniti aut qui.', 'Commodi eos officia autem cupiditate.', 'Sunt modi rem dolor sint architecto omnis. Voluptatibus quibusdam consequatur et eveniet. Delectus temporibus natus eligendi nisi qui eligendi qui. Ut reprehenderit fuga consectetur sed voluptatem.', '3', 'distinctio-laudantium-sunt-deleniti-aut-qui', 4, 2, 2, 2, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(17, 'Doloremque deserunt sint animi impedit culpa quas.', 'Quis ad dolores eos libero sed at.', 'Doloribus quo dignissimos sunt saepe et aut dolorem. Et qui maiores aliquam fugiat rerum. Veniam hic ipsa minima quod vel facere. Ipsum quia debitis soluta possimus modi molestiae aut.', '2', 'doloremque-deserunt-sint-animi-impedit-culpa-quas', 3, 1, 2, 4, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(18, 'Velit vel vitae ipsam et nesciunt maxime.', 'Nesciunt et voluptas placeat pariatur omnis quibusdam in.', 'Iste quis qui necessitatibus veniam consequuntur non. Quam sapiente accusantium minus delectus. Hic et libero laboriosam nihil eos. Totam saepe ea provident ea neque. Sequi quos eveniet aut explicabo soluta nihil.', '1', 'velit-vel-vitae-ipsam-et-nesciunt-maxime', 4, 2, 3, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(19, 'Quis hic beatae voluptas nisi.', 'Aut totam possimus eligendi nostrum ut sunt.', 'Eos rerum itaque numquam excepturi totam consequatur minima itaque. Est officiis nemo consequuntur. Velit fugit laborum repudiandae optio.', '2', 'quis-hic-beatae-voluptas-nisi', 2, 2, 1, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(20, 'Porro vitae consequuntur commodi facilis eos.', 'Maiores facere voluptate mollitia excepturi pariatur iure.', 'Aut itaque dolores fugit officia distinctio esse. Et accusantium aperiam qui ut est illum. Aut expedita accusamus voluptas voluptatem accusantium quo reprehenderit. Optio tenetur eligendi vel voluptatibus.', '2', 'porro-vitae-consequuntur-commodi-facilis-eos', 2, 3, 2, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(21, 'Aut non voluptate asperiores cum incidunt eligendi.', 'Laboriosam velit voluptate et doloremque.', 'Nobis adipisci animi error adipisci soluta eaque nemo. Totam vel praesentium velit aliquam et vel sequi doloremque. Dolor soluta occaecati quis velit. Consequatur eos eveniet error vel quasi nobis optio.', '2', 'aut-non-voluptate-asperiores-cum-incidunt-eligendi', 1, 2, 3, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(22, 'Natus omnis accusamus porro dolores.', 'Consequatur id autem tempore at sapiente iure rem.', 'Enim vel et quis quis ea sequi facilis. Beatae perferendis harum officia veritatis deserunt. Eius et unde assumenda molestiae. Et nihil aut doloribus. Dolorem expedita in voluptatem nostrum.', '1', 'natus-omnis-accusamus-porro-dolores', 2, 2, 1, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(23, 'Voluptatum eum architecto animi nisi.', 'Sed temporibus qui vel ut perspiciatis et magnam.', 'Esse totam inventore laudantium explicabo facilis minima magnam. Ut similique est a maiores voluptatem iure sit. Odit sunt at tempora. Est facilis quo sed quia.', '1', 'voluptatum-eum-architecto-animi-nisi', 3, 3, 2, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(24, 'Odio sed similique sint et.', 'Vitae ratione totam quod non eum doloribus qui.', 'Mollitia ratione dolorem minus quo cum odit. Sit quibusdam vitae dolores voluptatibus quia magni earum. Quos molestias dolor adipisci et sed explicabo quibusdam itaque. Sit voluptates molestias aut aspernatur ex aspernatur sed voluptatibus.', '3', 'odio-sed-similique-sint-et', 4, 1, 3, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(25, 'Doloribus quasi id possimus quia tenetur sed.', 'Possimus est voluptas sunt.', 'Laudantium aspernatur nisi error sed. Non quibusdam nostrum provident fuga ut. Cupiditate et magnam minus deserunt. Non debitis autem ab neque voluptatum ducimus quo eius.', '2', 'doloribus-quasi-id-possimus-quia-tenetur-sed', 3, 3, 2, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(26, 'Consequuntur autem consequatur accusamus nobis.', 'Dolorem quos sit ad eveniet facere delectus tenetur.', 'Soluta autem et nobis eum non id. Omnis voluptatibus ea praesentium est aut ea mollitia. Repellendus qui sit soluta modi.', '2', 'consequuntur-autem-consequatur-accusamus-nobis', 4, 3, 3, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(27, 'Ut error quis hic.', 'Expedita quasi sint sed ut quia impedit ratione.', 'Et aut vero harum vel deleniti et. Alias recusandae debitis sequi occaecati quod quos.', '3', 'ut-error-quis-hic', 4, 3, 2, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(28, 'Molestias veritatis perspiciatis ut facilis quos.', 'Accusantium laboriosam eligendi ut nisi nobis molestias.', 'Laboriosam commodi corrupti in culpa exercitationem nesciunt et. Est inventore culpa voluptatem tempora illo. Id debitis et aut esse architecto beatae.', '2', 'molestias-veritatis-perspiciatis-ut-facilis-quos', 2, 1, 3, 3, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(29, 'Fugit aut suscipit doloribus fugit rerum natus omnis consequatur.', 'Aut accusantium minima sed laborum cum.', 'Consequatur dignissimos laudantium hic assumenda. Quae ut fugit dolorem aliquam quos. Nemo ad porro et blanditiis repudiandae.', '3', 'fugit-aut-suscipit-doloribus-fugit-rerum-natus-omnis-consequatur', 1, 2, 1, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(30, 'Expedita quam illum ut.', 'Dolor velit soluta quia nihil necessitatibus sunt quasi.', 'Totam deleniti sunt eligendi et est expedita. Ut ut reiciendis sapiente fugit accusamus nesciunt rerum. Voluptas perferendis vero ab accusantium ea.', '2', 'expedita-quam-illum-ut', 1, 2, 3, 2, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(31, 'Ducimus omnis rerum facilis autem.', 'Quia eius excepturi qui atque reiciendis.', 'Ut eligendi nam ea in in est consequuntur. Omnis asperiores voluptas suscipit rerum. Similique beatae fugit nesciunt aliquid modi cupiditate consequatur. Laborum nobis cupiditate nihil.', '2', 'ducimus-omnis-rerum-facilis-autem', 2, 2, 2, 1, '2022-05-18 14:58:29', '2022-05-18 14:58:29', NULL),
(32, 'Dolores sunt aut sit necessitatibus aut recusandae accusamus.', 'Occaecati veritatis vitae officia qui rerum sit.', 'Debitis et error sed molestias. Qui natus error sed debitis. Molestiae voluptas ea et ex fugiat possimus.', '1', 'dolores-sunt-aut-sit-necessitatibus-aut-recusandae-accusamus', 1, 1, 1, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(33, 'Molestiae et qui enim ea porro nobis corporis.', 'Rem unde aliquam eveniet omnis ullam et.', 'Est nihil et molestiae ut quia odio maiores. Ad consequatur asperiores perspiciatis sed voluptatum. Autem voluptas ut velit temporibus deleniti ut sed. Ducimus dolorum magni quia tempore quam optio quaerat.', '1', 'molestiae-et-qui-enim-ea-porro-nobis-corporis', 2, 3, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(34, 'Sed sed ipsum reprehenderit tenetur temporibus beatae iste.', 'Excepturi sapiente perferendis commodi exercitationem ipsum occaecati amet.', 'Modi veniam assumenda fugit id. Voluptas omnis et voluptas vero nisi iusto eveniet. Aut consequatur veritatis autem velit eum qui fugit.', '1', 'sed-sed-ipsum-reprehenderit-tenetur-temporibus-beatae-iste', 3, 3, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(35, 'Esse quis atque sed et voluptatem.', 'Suscipit et consequatur minus dolorem.', 'Corrupti quaerat et illum sed ea qui. Est illum quis veritatis dolorum. Ut repudiandae delectus ut blanditiis suscipit.', '2', 'esse-quis-atque-sed-et-voluptatem', 4, 1, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(36, 'Delectus molestias laboriosam aut quis.', 'Est dolor dolores debitis.', 'Pariatur totam molestiae sint doloremque sapiente temporibus culpa fugit. Ullam voluptas omnis sed fugit. Et quae voluptates eum est id veritatis. Eius asperiores est maxime eos.', '1', 'delectus-molestias-laboriosam-aut-quis', 2, 3, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(37, 'Inventore qui animi labore id necessitatibus quae distinctio.', 'Quia molestiae ex ut eos.', 'Nisi quod ut dolores non facere magnam. Quo fuga illum in dolorem placeat. In et consequatur minima aspernatur ut. Explicabo quae dolor consequuntur ab cum nesciunt.', '1', 'inventore-qui-animi-labore-id-necessitatibus-quae-distinctio', 4, 1, 1, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(38, 'Tenetur exercitationem consequatur iure distinctio necessitatibus.', 'Sed est iusto asperiores tempore aliquid debitis.', 'Voluptatem dolorum consectetur provident velit et beatae. Illum sit et at et nostrum eligendi. Sit aliquam quo et perspiciatis et.', '2', 'tenetur-exercitationem-consequatur-iure-distinctio-necessitatibus', 1, 3, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(39, 'Voluptates velit quo ullam reprehenderit.', 'Possimus aut dolores quo sed.', 'Enim quas omnis delectus natus non nesciunt. Eligendi molestiae aut nulla mollitia. Praesentium voluptas occaecati error autem in qui. Atque harum nihil adipisci sunt nihil ab.', '3', 'voluptates-velit-quo-ullam-reprehenderit', 2, 1, 1, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(40, 'Voluptatum dolores mollitia vel sed autem.', 'Aut eveniet voluptate et labore eveniet sed.', 'Temporibus voluptas est consequuntur voluptas. Ipsam numquam error eum aut et distinctio quas. Eius facere enim ipsa praesentium. Provident est aut mollitia excepturi quod quo eum.', '1', 'voluptatum-dolores-mollitia-vel-sed-autem', 2, 1, 3, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(41, 'Et sit quia culpa sunt debitis modi officia.', 'Voluptatem praesentium voluptatum consectetur ipsum minus quaerat quaerat.', 'Maxime molestiae ea voluptatibus officia mollitia. Molestias et architecto qui aut omnis magnam. Ut voluptas sed non accusantium sit.', '3', 'et-sit-quia-culpa-sunt-debitis-modi-officia', 3, 3, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(42, 'Dolores sunt et id quibusdam ut.', 'Architecto aliquam totam eum sint consequatur cupiditate.', 'Aliquam impedit dolorum itaque explicabo et blanditiis qui. Corporis aut corporis ut id natus assumenda. Excepturi distinctio repellat dolorum possimus. Tempora aut et ipsa.', '2', 'dolores-sunt-et-id-quibusdam-ut', 1, 2, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(43, 'Facilis quasi repellat omnis ex reiciendis voluptatem id.', 'Dignissimos sunt sint consequuntur dolores numquam.', 'Molestiae nam et molestiae dicta commodi beatae. Laborum ullam ut esse nulla. Autem dolorem esse eos. Rerum impedit ut voluptatem impedit in temporibus fugiat. In quidem veniam molestiae voluptatem autem.', '1', 'facilis-quasi-repellat-omnis-ex-reiciendis-voluptatem-id', 3, 3, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(44, 'Delectus et cumque voluptatem tempore necessitatibus.', 'Nostrum tempore quae culpa.', 'Amet voluptate sit et qui fuga debitis quaerat. Accusamus atque sequi voluptatem aspernatur. Deleniti commodi qui non non veritatis aut. Ratione quis illum ut quo est id.', '2', 'delectus-et-cumque-voluptatem-tempore-necessitatibus', 3, 2, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(45, 'Voluptatem sit atque hic voluptatum et ab deleniti.', 'Nostrum repudiandae explicabo sed dicta.', 'Ducimus et sed dolorum quibusdam ex ipsa aliquam. Sit voluptatem excepturi pariatur velit. Quis aut dolores autem libero perspiciatis consequatur quo maxime. Qui tenetur consequatur enim omnis inventore.', '3', 'voluptatem-sit-atque-hic-voluptatum-et-ab-deleniti', 4, 1, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(46, 'Voluptatem saepe excepturi ducimus et.', 'Quos repellendus eos minima iure.', 'Accusantium soluta aliquam accusamus voluptas. Corporis neque repellendus culpa est qui qui quod. Et quisquam quaerat et eos porro voluptatem.', '3', 'voluptatem-saepe-excepturi-ducimus-et', 4, 1, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(47, 'Et aspernatur sapiente placeat recusandae aut iusto.', 'Sit dignissimos aperiam nisi vel consectetur repudiandae sint.', 'Nobis eos cumque voluptas quas. Maiores sapiente similique nihil porro ut. Molestias iste sapiente esse reiciendis accusamus placeat pariatur voluptatem.', '1', 'et-aspernatur-sapiente-placeat-recusandae-aut-iusto', 3, 1, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(48, 'Debitis ipsam rem ut quia ad tenetur possimus.', 'Amet aliquam aliquid est eveniet.', 'Iste autem aut omnis possimus. Et est earum tenetur aliquid. Ut ea laboriosam ipsa perferendis omnis.', '3', 'debitis-ipsam-rem-ut-quia-ad-tenetur-possimus', 1, 2, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(49, 'Ut commodi nobis rerum facere.', 'Incidunt velit unde et similique.', 'Aut sint eum dolore totam enim tempora. Deserunt reprehenderit quibusdam nostrum hic. Neque in ea velit quia ducimus ut. Et dicta quia sequi deleniti recusandae.', '3', 'ut-commodi-nobis-rerum-facere', 1, 1, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(50, 'Aut distinctio tenetur qui eum.', 'Itaque vitae odit non accusantium vel consequatur.', 'Et dignissimos sint corporis fugiat dolorem debitis corporis. Consequatur sunt non voluptatem voluptas nam sed. Cupiditate exercitationem quae officiis distinctio. Harum eum facere iusto perferendis aliquam itaque et.', '2', 'aut-distinctio-tenetur-qui-eum', 1, 3, 3, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(51, 'Vel qui dolores eum tenetur quis.', 'Assumenda eius et rerum soluta minima quo doloremque voluptas.', 'Aut nihil distinctio esse eum id. Harum eius totam aut praesentium autem enim quam. Repellendus incidunt vel eius et voluptatem vel.', '3', 'vel-qui-dolores-eum-tenetur-quis', 1, 3, 1, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(52, 'Alias ut accusamus neque soluta repellendus recusandae repellat.', 'Reprehenderit vel aspernatur aperiam tempore fugit illo.', 'Harum hic aspernatur autem magni. Et occaecati eum reprehenderit sit.', '3', 'alias-ut-accusamus-neque-soluta-repellendus-recusandae-repellat', 2, 1, 3, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(53, 'Qui eum id ipsa nobis alias expedita.', 'Architecto debitis aut sint vero odit.', 'Tenetur laudantium inventore iure autem accusamus praesentium architecto aperiam. Consequatur velit explicabo alias fugit. Quisquam maiores quae neque atque ad ut nihil.', '3', 'qui-eum-id-ipsa-nobis-alias-expedita', 3, 3, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(54, 'At atque iste error ut recusandae dolorem error laboriosam.', 'Placeat sed quia laudantium non aut.', 'Dolore neque error ipsa quis. Non laboriosam et ut repellat eum exercitationem temporibus. Quo accusantium dignissimos sed voluptas.', '3', 'at-atque-iste-error-ut-recusandae-dolorem-error-laboriosam', 3, 1, 2, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(55, 'Facilis quas possimus vitae et.', 'Quia temporibus accusantium eveniet.', 'Ut tempora temporibus quis fuga officiis unde quas. Corporis quos consequatur recusandae saepe dolores quae aut reprehenderit. Voluptatibus quisquam numquam et dolores repellat iure cupiditate incidunt.', '1', 'facilis-quas-possimus-vitae-et', 3, 2, 3, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(56, 'Quia architecto similique velit sequi unde.', 'Occaecati voluptas laboriosam dolorem iusto aperiam et necessitatibus.', '<p>Vel dolore quos dolorem praesentium harum tenetur. Voluptatem et rerum qui. Est est occaecati sint nulla soluta eos. Quia eius aut aut impedit facilis. Qui eveniet ea at temporibus.</p>', '1', 'quia-architecto-similique-velit-sequi-unde', 1, 3, 2, 2, '2022-05-18 14:58:30', '2022-05-19 13:18:17', NULL),
(57, 'Deleniti ab optio maiores et saepe ut dicta.', 'Eaque illo error maiores itaque ad quas.', 'Unde quia saepe ut quia ex cum. Voluptas qui error fugiat maxime tenetur. Eos autem beatae qui minus est et.', '3', 'deleniti-ab-optio-maiores-et-saepe-ut-dicta', 2, 3, 1, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(58, 'Facere tenetur quo sapiente.', 'Eum mollitia neque nihil.', 'Qui libero est et rerum repellendus ut. Delectus quos temporibus aut voluptatibus beatae consequatur sit vel. Natus eum corporis laborum. Et et dignissimos veritatis atque esse ut beatae minus.', '1', 'facere-tenetur-quo-sapiente', 4, 1, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(59, 'Voluptas esse voluptate nihil dicta nesciunt amet omnis.', 'Minus esse ea odit non.', 'Magnam cum consequatur molestiae repudiandae temporibus quia ea. Beatae architecto totam voluptas impedit. Veritatis laboriosam aliquam harum voluptatem aliquam id. Laborum dolorem rerum tempora qui.', '3', 'voluptas-esse-voluptate-nihil-dicta-nesciunt-amet-omnis', 3, 2, 3, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(60, 'Iure quisquam aut commodi voluptatem.', 'Ea praesentium consequatur et tempora.', 'Nobis tenetur numquam qui. Est impedit adipisci impedit quibusdam in officia distinctio qui. Omnis ut voluptas expedita temporibus.', '3', 'iure-quisquam-aut-commodi-voluptatem', 3, 2, 3, 1, '2022-05-18 14:58:30', '2022-05-27 14:12:22', NULL),
(61, 'Et et quo facere.', 'Voluptatem deleniti rerum officiis aspernatur deleniti impedit recusandae.', 'Rem placeat nobis inventore cupiditate incidunt. Consectetur quia error officia tempore quo. Modi ipsam maxime doloribus ut sed rerum et. Ut labore saepe ut molestias fuga id cumque harum.', '1', 'et-et-quo-facere', 4, 2, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(62, 'Et praesentium adipisci quis et dicta qui.', 'Rerum quia voluptates officia recusandae.', 'Corporis doloremque illo sit nostrum. Voluptates sequi distinctio in. Placeat aperiam consequatur omnis quia dolores ad. Aliquid nemo culpa ut perferendis possimus repudiandae adipisci veniam.', '3', 'et-praesentium-adipisci-quis-et-dicta-qui', 3, 2, 1, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(63, 'Dolore impedit laborum unde vitae.', 'Officiis laboriosam sequi voluptates officiis.', 'Mollitia aut eaque sunt accusamus. Quae non eos eos esse sunt voluptatem.', '3', 'dolore-impedit-laborum-unde-vitae', 1, 1, 3, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(64, 'Voluptas similique quis et a totam.', 'Eum omnis voluptas voluptates impedit qui odit.', 'Officia unde officia consequatur delectus. Aliquid commodi et porro. Voluptatem esse libero repellendus vel facilis soluta dolor. Et qui distinctio ex dolor itaque ea.', '3', 'voluptas-similique-quis-et-a-totam', 2, 1, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(65, 'Doloremque consequuntur ut expedita quo quidem voluptates ducimus.', 'Facilis est amet eos magni corporis labore eligendi.', 'Aliquam sed impedit omnis excepturi dolor reprehenderit voluptatibus. Illum voluptatibus perspiciatis sit repudiandae. Id illo necessitatibus est adipisci iste placeat. Eum eligendi veritatis voluptatem eum quis consequuntur.', '2', 'doloremque-consequuntur-ut-expedita-quo-quidem-voluptates-ducimus', 3, 3, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(66, 'Tempore cupiditate placeat et sed a enim.', 'Quo enim iusto impedit aliquam qui.', 'Quam facilis quod dolores. Tempore soluta cupiditate porro voluptas. Cumque qui aut nisi corrupti labore. Ut sed doloremque necessitatibus occaecati consequuntur ea.', '1', 'tempore-cupiditate-placeat-et-sed-a-enim', 1, 2, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(67, 'Qui natus odio nihil repudiandae.', 'Veniam similique optio quo quisquam pariatur quos et nobis.', 'Et autem qui qui sed quia minus est. Sit ipsam veritatis ducimus. Provident aut perferendis temporibus. Nobis architecto blanditiis totam similique.', '3', 'qui-natus-odio-nihil-repudiandae', 3, 3, 1, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(68, 'Eos a perspiciatis qui fugiat ab enim.', 'Incidunt at rerum et sunt ut et inventore necessitatibus.', 'Laboriosam deserunt tenetur autem sunt molestiae officia cum. Mollitia iure nam labore enim. Voluptas eligendi et libero et corrupti et et. Tempore quaerat rerum omnis dolores aut est aut quis.', '3', 'eos-a-perspiciatis-qui-fugiat-ab-enim', 1, 2, 3, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(69, 'Dignissimos libero soluta adipisci necessitatibus.', 'Quia quod at sint voluptatem quidem occaecati est.', 'Perspiciatis neque ipsa omnis qui consequatur eveniet. Quo rerum placeat amet ad quo soluta atque. Molestiae sed neque molestiae debitis. Deserunt aliquam sed nesciunt ducimus aspernatur. Excepturi ipsa quis neque autem ipsam cum.', '1', 'dignissimos-libero-soluta-adipisci-necessitatibus', 2, 2, 3, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(70, 'In voluptatem aut inventore.', 'Nemo hic facere vel id.', 'Qui veritatis eos vitae excepturi atque dolorem provident. Ipsum vitae perspiciatis voluptates ut cupiditate. Voluptas eos amet quo officiis perferendis et qui. In accusantium impedit a.', '2', 'in-voluptatem-aut-inventore', 1, 1, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(71, 'Culpa distinctio ab aliquid ut.', 'Necessitatibus corporis unde culpa voluptatem numquam.', 'Aut veniam quam aliquid ut. Animi nostrum ex hic est.', '2', 'culpa-distinctio-ab-aliquid-ut', 4, 3, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(72, 'Molestias error fuga aspernatur voluptate.', 'Quae iusto magni qui dolorum omnis et odit.', 'Fugit nesciunt consequuntur doloremque error nam. Aliquid ducimus voluptatem officia mollitia libero. Odio veniam aliquam sunt est itaque dolorem culpa.', '1', 'molestias-error-fuga-aspernatur-voluptate', 3, 2, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(73, 'Unde veritatis minima at sunt nisi.', 'Id aperiam est maiores non numquam sed voluptas cum.', 'Nemo rerum in deleniti. Ducimus quia blanditiis soluta sint ut totam. Sed soluta ipsum temporibus consequatur. Cupiditate vel et qui impedit iure.', '3', 'unde-veritatis-minima-at-sunt-nisi', 4, 2, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(74, 'Officia voluptatem debitis ex autem atque.', 'Fugiat aut ducimus laborum unde dolorum sunt soluta quos.', 'Molestiae omnis saepe distinctio dolore. Harum voluptate sed id dolores.', '1', 'officia-voluptatem-debitis-ex-autem-atque', 4, 3, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(75, 'EDITAR PUBLI imag', 'Quia aut ipsum quam distinctio quia consequuntur.', '<p>Et doloremque doloribus sint error iure quos est. Enim dicta est dicta vitae deleniti facere. Commodi rerum excepturi nemo ullam alias veniam optio. Minus et qui perspiciatis laborum.</p>', '3', 'editar-publi-imag', 1, 3, 3, 4, '2022-05-18 14:58:30', '2022-05-20 10:24:58', NULL),
(76, 'Id dolorem in aliquid eum officia doloremque facere.', 'Dolore quibusdam dolore earum similique illum nostrum dolores.', 'Ut ipsum officiis harum dolorem eum distinctio. Sequi saepe sunt rerum ea a velit. Assumenda est nisi quibusdam eligendi voluptates voluptatem blanditiis.', '3', 'id-dolorem-in-aliquid-eum-officia-doloremque-facere', 4, 2, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(77, 'Rerum quibusdam iusto voluptas expedita.', 'Quibusdam eius aut quas rerum qui alias atque.', 'Non omnis voluptatem at consequatur rem autem ut. Molestiae ratione dolorem velit quam.', '3', 'rerum-quibusdam-iusto-voluptas-expedita', 3, 3, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(78, 'Perferendis provident eum pariatur repudiandae et.', 'Aspernatur voluptates vel deleniti quia facere maiores dolorum aut.', 'Aspernatur molestias est quas occaecati et earum. Eum autem sed exercitationem eveniet voluptatem velit. Quisquam eius eum est neque. Odio odio provident est accusantium.', '3', 'perferendis-provident-eum-pariatur-repudiandae-et', 2, 1, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(79, 'Sunt exercitationem molestiae dignissimos omnis odit inventore.', 'Illum officia ducimus quos veniam delectus.', 'Magnam ipsa laudantium perferendis. Mollitia quisquam esse explicabo necessitatibus dolore ut. Veritatis aspernatur amet quae deserunt molestiae.', '3', 'sunt-exercitationem-molestiae-dignissimos-omnis-odit-inventore', 3, 2, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(80, 'A consectetur doloremque at numquam occaecati aut dolor.', 'Quibusdam aliquid reprehenderit aut perferendis.', 'Reiciendis aut deleniti totam doloribus quidem. Praesentium dolorum est minus quia. Ipsam totam harum ipsam eum. Sint blanditiis similique eligendi illo et.', '2', 'a-consectetur-doloremque-at-numquam-occaecati-aut-dolor', 4, 2, 3, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(81, 'Aut fugit illum impedit nihil reprehenderit molestiae.', 'Aperiam aut molestiae impedit veritatis sapiente totam.', 'Tenetur voluptas quaerat quibusdam vero voluptatem. Qui vel quisquam ipsa neque iusto dolorem. Qui dolor nisi atque autem molestiae illum doloribus. Accusamus inventore officiis expedita aut officiis et.', '2', 'aut-fugit-illum-impedit-nihil-reprehenderit-molestiae', 3, 2, 3, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(82, 'Consequatur et atque voluptate quos harum enim vel sit.', 'Voluptas laboriosam dolor ad nisi ullam ducimus amet.', 'Perferendis reiciendis dolorum voluptatem dolorum voluptas. Aut aut ducimus nam. Eum non deleniti harum. Doloremque totam ut voluptatibus est non dolorem tenetur.', '2', 'consequatur-et-atque-voluptate-quos-harum-enim-vel-sit', 3, 2, 1, 1, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(83, 'Autem ut quo qui qui est dignissimos aliquam molestiae.', 'Corrupti alias tempore facere quidem qui et in.', 'Dignissimos qui laudantium sequi omnis. Et quia placeat itaque id.', '1', 'autem-ut-quo-qui-qui-est-dignissimos-aliquam-molestiae', 2, 1, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(84, 'Similique velit magni tenetur odit et.', 'Quia sunt quo iure voluptatem eveniet repellendus velit.', 'Provident consectetur magnam est sint ut totam assumenda rerum. Ut eos beatae quidem aut. Ut quia at quia praesentium perferendis.', '1', 'similique-velit-magni-tenetur-odit-et', 3, 3, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(85, 'Perferendis distinctio et id voluptatem.', 'Aut dolor error a excepturi.', 'Neque fugiat corrupti atque. Dolor non et dignissimos et aliquam. Aut cupiditate soluta atque rerum corporis vitae aliquam. Repellat adipisci quo fugit assumenda deleniti odio ipsum.', '1', 'perferendis-distinctio-et-id-voluptatem', 4, 3, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(86, 'Esse accusamus repellendus nemo doloremque perferendis non perferendis.', 'Corporis in rerum omnis.', 'Quidem eius aut iusto ad blanditiis exercitationem culpa aut. Debitis dolorum qui blanditiis molestias placeat veritatis. Et dolorem autem possimus veniam.', '3', 'esse-accusamus-repellendus-nemo-doloremque-perferendis-non-perferendis', 2, 3, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(87, 'Tempora rerum qui nisi aut hic.', 'Omnis aut est sit distinctio nostrum officia.', 'Est accusantium qui harum animi. Maiores dignissimos doloribus nulla aut aut qui maiores. Sed doloremque mollitia ut quod. Dicta quibusdam et eum aperiam.', '3', 'tempora-rerum-qui-nisi-aut-hic', 3, 2, 3, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(88, 'Repudiandae enim voluptatibus ullam perspiciatis doloribus aut et eveniet.', 'Suscipit sed maiores qui odit necessitatibus.', 'Qui minus est voluptatum dolor. Assumenda voluptatem qui omnis est. Ad velit saepe similique veritatis maiores. Inventore dolores consectetur perferendis.', '3', 'repudiandae-enim-voluptatibus-ullam-perspiciatis-doloribus-aut-et-eveniet', 3, 3, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(89, 'Nobis quos doloremque modi beatae.', 'Placeat quibusdam consequatur iste ipsum quia illo iusto vitae.', 'Et mollitia id veritatis omnis sunt id aut optio. Voluptatum itaque est eligendi magni. Sapiente mollitia ea voluptas autem. Eius sequi asperiores voluptas vel sed quidem.', '1', 'nobis-quos-doloremque-modi-beatae', 1, 3, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(90, 'Accusantium quam at nisi sunt recusandae possimus consequuntur.', 'Voluptatem beatae ut commodi atque numquam maxime.', 'Tempore sed et iure temporibus unde non. Aspernatur autem a aut ratione placeat. Laudantium exercitationem possimus consectetur expedita animi. Aut debitis suscipit et provident est.', '3', 'accusantium-quam-at-nisi-sunt-recusandae-possimus-consequuntur', 3, 3, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(91, 'Sint repellendus repellendus voluptatem voluptatem et.', 'Consequatur velit aperiam ipsum dicta.', 'Earum aut laboriosam non itaque. Mollitia eveniet harum officia tenetur sapiente aperiam et facilis. Nemo repudiandae laudantium magni vel sequi. Perferendis alias facere tempora eum et vero a.', '2', 'sint-repellendus-repellendus-voluptatem-voluptatem-et', 1, 2, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(92, 'editando', 'Dolorem qui dolor velit sunt saepe officia est ipsam.', '<p>Qui eum et hic sit dignissimos quis iure dolor. Omnis aperiam at culpa atque non veniam repellendus. Tempore perferendis nihil earum ut sequi perferendis. Nisi aspernatur praesentium ea aperiam dolorem aperiam ut. Quos tenetur molestiae enim consequatur vel.</p>', '1', 'editando', 1, 3, 1, 2, '2022-05-18 14:58:30', '2022-05-19 07:33:09', NULL),
(93, 'Et blanditiis vel quia eos saepe odio ut.', 'Sint ut quisquam vero.', 'Accusamus vel sit quia impedit quis eos. Dolor ratione dolores amet libero molestiae veniam. Aut architecto aperiam vel voluptatem. Dolores voluptas ut aut sit quam nihil maxime.', '3', 'et-blanditiis-vel-quia-eos-saepe-odio-ut', 3, 3, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(94, 'Quam occaecati et id iusto et animi dolor.', 'Laborum asperiores quasi rerum sapiente voluptas illo.', 'Mollitia et voluptatem veniam similique. Quidem expedita exercitationem libero nemo autem. Perspiciatis animi minus corrupti ut itaque. Asperiores sit ut rerum repellendus illo qui occaecati molestiae.', '2', 'quam-occaecati-et-id-iusto-et-animi-dolor', 2, 1, 2, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(95, 'Repellendus tenetur dolores hic et.', 'Qui aperiam eum dolor quia sint qui et harum.', 'Eum accusantium quo delectus iure nobis. Amet ab minima tenetur possimus suscipit qui earum. Et eaque molestiae sed iusto. Itaque nam at officiis optio animi perferendis optio.', '2', 'repellendus-tenetur-dolores-hic-et', 2, 2, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(96, 'Animi et beatae aut porro expedita.', 'Iusto et consequatur ea nihil dolorum molestiae ut aut.', 'Eum culpa id est saepe incidunt. Ab voluptatem itaque hic sunt ratione neque at non. Eveniet voluptas repellendus quas voluptas ratione dignissimos alias. Officiis asperiores et consectetur in dignissimos neque. Qui laudantium id aperiam aut fuga.', '2', 'animi-et-beatae-aut-porro-expedita', 4, 1, 2, 2, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(97, 'Velit sed incidunt id est dolores.', 'Ratione reprehenderit quis deleniti voluptas quod totam labore.', 'Molestiae et quia sed dolores. Sed fugiat aut harum quia et. Vero rem dolores ut at molestias voluptatem dolorem. Sunt vero in earum nesciunt doloribus sunt recusandae.', '2', 'velit-sed-incidunt-id-est-dolores', 2, 2, 1, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(98, 'Commodi sint magnam est quia corrupti molestias pariatur.', 'Est repellendus aut necessitatibus voluptatem consequuntur non quia.', 'Autem quia optio architecto deleniti nemo aut dolorem possimus. Quod inventore voluptatem corporis qui. Possimus qui nihil voluptas ipsa.', '2', 'commodi-sint-magnam-est-quia-corrupti-molestias-pariatur', 4, 1, 2, 4, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(99, 'Molestiae molestiae facilis voluptas repellat sequi quia voluptatum voluptatem.', 'Animi mollitia error nostrum enim et.', 'Ratione debitis perferendis harum tenetur qui. Voluptatem odio omnis neque error et in praesentium. Velit quibusdam molestiae officiis odit.', '2', 'molestiae-molestiae-facilis-voluptas-repellat-sequi-quia-voluptatum-voluptatem', 2, 1, 1, 3, '2022-05-18 14:58:30', '2022-05-18 14:58:30', NULL),
(100, 'Architecto tenetur soluta voluptatem.', 'Unde ea incidunt maxime dignissimos aspernatur.', 'Harum porro eaque illo earum quisquam. Explicabo quo omnis corrupti ut est. Quis dolores itaque consequatur in. Voluptatem nesciunt saepe quidem.', '1', 'architecto-tenetur-soluta-voluptatem', 4, 3, 3, 3, '2022-05-18 14:58:30', '2022-05-19 12:01:28', NULL),
(101, 'Laravel 9 - Crea Aplicaciones y Sitios Web con PHP 8 y MVC', 'Aprende Laravel y Comienza a Crear Aplicaciones Web Dinámicas, Interactivas y Seguras', '<p>Bienvenido al curso de <strong>Laravel 9 - Crea Aplicaciones y Sitios Web con PHP 8 y MVC</strong></p><p>En este curso aprenderás todo lo que necesitas saber de <strong>Laravel para obtener un empleo o crear tu emprendimiento digital!</strong></p><p>Laravel es un Framework con baterías incluidas, eso quiere decir que ya tiene:</p><blockquote><p>Creación y Autenticación de Usuarios</p><p>Hash para passwords</p><p>Paginación</p><p>Subida de Archivos</p><p>Seguridad y Protección</p><p>Webpack para añadir CSS o Librerías JS</p><p>Envio de Emails</p><p>Confirmación de Cuentas</p><p>Sanitización de Inputs</p><p><strong>y mucho más!!</strong></p></blockquote>', '3', 'laravel-9-crea-aplicaciones-y-sitios-web-con-php-8-y-mvc', 1, 2, 1, 1, '2022-05-27 11:37:59', '2022-06-02 11:40:47', NULL),
(102, 'pruebas crear', 'subt', '<p>descripcion cursos</p>', '1', 'pruebas-crear', 101, 2, 3, 1, '2022-05-30 10:28:56', '2022-05-30 10:28:56', NULL),
(103, 'asd', 'asdasd', '<p>dasdas</p>', '1', 'asd', 1, 1, 1, 1, '2022-06-02 00:19:30', '2022-06-02 00:19:30', NULL),
(104, 'crear 2', 'crear 2', '<p>preubas creando</p>', '3', 'crear-2', 1, 1, 1, 1, '2022-06-02 09:30:08', '2022-06-02 09:32:56', NULL),
(105, 'Dominado Laravel', 'Laravel, creación de aplicaciones', '<p>En este curso aprenderemos desde cero, a programar aplicaciones web utilizando el framework más popular de php, LARAVEL.</p>', '3', 'dominado-laravel', 101, 1, 1, 2, '2022-06-02 11:57:32', '2022-06-02 12:01:32', NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `courses`
--
ALTER TABLE `courses`
  ADD PRIMARY KEY (`id`),
  ADD KEY `courses_user_id_foreign` (`user_id`),
  ADD KEY `courses_level_id_foreign` (`level_id`),
  ADD KEY `courses_category_id_foreign` (`category_id`),
  ADD KEY `courses_price_id_foreign` (`price_id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `courses`
--
ALTER TABLE `courses`
  MODIFY `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=106;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `courses`
--
ALTER TABLE `courses`
  ADD CONSTRAINT `courses_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL,
  ADD CONSTRAINT `courses_level_id_foreign` FOREIGN KEY (`level_id`) REFERENCES `levels` (`id`) ON DELETE SET NULL,
  ADD CONSTRAINT `courses_price_id_foreign` FOREIGN KEY (`price_id`) REFERENCES `prices` (`id`) ON DELETE SET NULL,
  ADD CONSTRAINT `courses_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
